### PR TITLE
Add UX Vision

### PR DESCRIPTION
**Pull request by PierreRochard**

### CODE REVIEW

**Comment by udiWertheimer** [comment]
Thanks for sharing this. Looks great!

Just a thought regarding syncing: I don't know how further along things are with Neutrino etc, but seeing as this is a wrapper/launcher and not Core/LND itself, I think we can take a different approach than they do, and just ship this launcher with an up-to-date, fully synced utxo set (with block data, if not pruned). (can be downloaded separately through the app). 

We can add sigs from different community members who sign off on the recent UTXO set to make it very difficult to forge, and open source that tool that can generate a commitment for the latest utxo set from another node, so that it can be verified deterministically.

This assumes more trust than a standard Bitcoin Core installation, but it makes a lot of sense for the launcher usecase, IMO it has some advantages over the neutrino security model.

**Comment by wiredcheetah** [comment]
@tomelvis, lightning teams seem to be working on ways to safely backup LN node state.

@udiWertheimer, If this team shipped it with a pruned datadir, It should query the drives for free space. If there is not enough free space, nudge the user to plug in an external drive. If there is enough free space, ask the user which drive to store the datadir.

Then it would fully* sync the node, (probably with -assumevalid at the default), shut down the pruned node, copy over it's wallet, and rescan that wallet. It could start up the pruned node again until the rescanning is done.

Not sure about the problems with running 2 bitcoind instances at the same time. Maybe the pruned node should be containerized.

**Comment by wiredcheetah** [comment]
@udiWertheimer, I do prefer the pruned node over SPV modes for the privacy benefits. A pruned node datadir would not be less safe than SPV since it has the block headers, unless i'm mistaken.

This should never be decoupled from syncing a full node in the background.

**Comment by SamAI-Software** [comment]
> Both nodes default to using Tor.

I genially like the idea of using Tor as a default setting, because **default settings matter**, but we have to think about all people, right? There are many regions where Tor is not working, and in the last few years there was a huge expansion of censorship technologies into smaller developing countries.
What can we do about it?
1. User should get info how to obtain bridges even if the official Tor project website is blocked, and set them up, ideally with 2-3 clicks.
2. There should be a back-up plan in case a user failed to get bridges, or they didn't work (yes, sometimes even bridges don't help).

**Comment by Kixunil** [comment]
I have tons of other suggestions, so I made another PR into this branch. :) See #202

**Comment by skimanner** [comment]
To prevent this being overlooked I would just like to point out that you mentioned this is in #2:

installer flow ends with check marked "Open Node Launcher"

A check mark that is checked by default should be on same screen for the option to auto load on boot and of course the traditional view readme option

**Comment by natefriedman** [comment]
My understanding is the purpose is to be the easiest, non-custodial way to get on lightning.  If so, Tor might be an unnecessary complexifier.    It increases points of failure, is impractical for initial block download, and is an incomplete privacy solution.

After all, 99% of the people using this software will start on an exchange, so they are not anonymous bitcoin users.   Unless I am missing something, the biggest advantage of tor in this setup is Pierre wouldn't know the IP of the private channels with him.  

Now I would love you see a "one-click" downloader that includes tor, lightning, mixing capabilities, etc.  (basically wasabi + lightining) but am not sure this would be the goal of this project.

**Comment by SamAI-Software** [comment]
@natefriedman without setting Tor as a default option, we are increasing a chance of LN becoming a tool of massive financial surveillance, especially after a deployment of [watchtowers](https://medium.com/crypto-punks/lightning-vs-raiden-2-can-we-solve-privacy-and-scalability-problems-of-watchtowers-and-e243f7793d19), since laymen will use one on-chain address for all off-chain transactions.

**Comment by natefriedman** [comment]
@SamAI-Software I guess I am still unclear what Tor provides in this senario.  Layman would use onchain bitcoin from a KYC'd source to open the channel, linking identity to their transactions.   If a watchtower is involved, it would see all of the off-chain transactions regardless and everything could be traced back.  No?

**Comment by SamAI-Software** [comment]
@natefriedman yes, you're right, in the worst case scenario LN will become a tool of massive surveillance, so Tor won't help. That's why it's important to discuss different designs and think about incentives models.
However, I can see a bright future as well:
1. P2P OTC trading platforms are on the rise (both centralized and decentralized), and most of them don't require any KYC.
2. The packages sent to privacy-oriented LN watchtowers are encrypted and don't have so much value, especially if sent via Tor.
The other problem is that certain designs of LN watchtowers will be able to associate together all transactions made by the same channel/account, which will make usage of Tor pointless, but that's another topic, which we're researching in the series of articles linked above.
Anyway, what I'm trying to say is that Tor is a great tool that should be always set by default, because it will help preserve privacy if we play it right on the other fields as well: privacy-oriented watchtowers, hubs, fiat gateways, etc.

**Comment by wiredcheetah** [comment]
@natefriedman , 
I think it's not likely that there is a region where TOR is illegal AND it's perfectly safe to use bitcoin openly in the panopticon. It's not even safe to publicly use bitcoin in a lot of places where TOR _is_ legal. Gun control and long police response times mean that bitcoiners in most regions are vulnerable. Someone in such a region should certainly not be using this node launcher over clearnet.

IBD taking too long over TOR is a real problem. best solution I can think is for getting the blockchain by sneakernet and verifying it with the node connected to TOR.

**Comment by benthecarman** [comment]
I think it'd be awesome if loop was eventually added so a user could press a button and instantly have inbound liquidity.  A button could be added to choose a channel to use loop on, and then have the ability to receive

**Comment by PierreRochard** [comment]
@benthecarman I think I'd leave that to the Wallet UI layer like Joule

**Pull request merged**
