### PR TITLE
Move from requirements.txt to Pipfile for deterministic builds

### PR DESCRIPTION
**Pull request by willcl-ark**
This PR moves the project from `pip`'s requirements.txt to `pipenv`'s Pipfile system providing better security of installed packages and deterministic builds.

This will require developers' (virtual) environment to be a specific python version (3.7.2) and all packages and their sub-dependencies also to have set versions.

For more information see:
https://pipenv.readthedocs.io/en/latest/
and
https://realpython.com/pipenv-guide/

### CODE REVIEW

**Comment by willcl-ark** [comment]
For the balance of conversation, you can read about how pipenv was found to not be a better solution for some project workflows here:

https://chriswarrick.com/blog/2018/07/17/pipenv-promises-a-lot-delivers-very-little/

I am not familiar-enough with the project to see yet if it will encounter the same issues that author did (I would recommend to read the comments below the article too, to see response from a pipenv dev), but I didn't find it difficult myself to set a single environment variable (once) telling pipenv to (always) create new venv's inside the project directory; in fish shell it's simply:

`set -x PIPENV_VENV_IN_PROJECT true`

Another alternative is to simply point `pipenv install` to your own python binary in  the venv you created yourself using:

`pipenv install --python=/path/to/venv/python/binary`

...but in doing this you do lose half the benefit of pipenv which is the combination of pip install and venv all-in-one.

**Comment by manecosta** [comment]
This seems in conflict with #87 since it requires a specific python version.

**Comment by PierreRochard** [comment]
@manecosta I thought about it some and I think deterministic build / added security is better than pleasing everyone by being python version agnostic https://github.com/PierreRochard/node-launcher/issues/91

An important aspect of this project is that we do package the binary ourselves, so the python versioning is only a problem for developers and I do expect them to be able to be on the latest version of python. 

Counter-argument would be that I'm putting more work on new contributors, the latest version of python isn't necessarily what's in their package manager. Are there other counter-arguments?

**Comment by justinmoon** [comment]
> `pipenv lock -r >> requirements.txt`

You could probably also do something like `pip install -r $(pipenv lock -r)`. 

If you go down this route you probably shouldn't bother actually creating the requirements.txt artifact ...

**Comment by justinmoon** [comment]
> `pipenv lock -r >> requirements.txt`

Would probably be better to pipe this directly to `pip install` and not actually create the requirements.txt file ...

**Pull request closed without merging**
