### PR TITLE
rebuilding configuration class

### PR DESCRIPTION
**Pull request by manecosta**
## Purpose

This PR rebuilds the _Configuration_ class to make it more manageable to work with keys that can have multiple values.

### Configuration Class

_Configuration_ now holds a list of ConfigurationProperty which has a key a value and an identifier (line number is used when first loaded).

Configuration also now implements a suite of methods to interact with configurations:

- _get_all_configurations_ - retrieves the whole configurations list
- _get_configurations_by_name_ - returns a list of matching configurations by name
- _get_configuration_by_identifier_ - returns a single configuration by identifier
- _remove_configuration_by_name_ - removes all configurations by name
- _remove_configuration_by_identifier_ - removes a single configuration by identifier
- _set_default_configuration_ - sets the value of a configuration if no value exists yet
- _edit_configuration_ - edits a configuration by its identifier
- _replace_configuration_ - removes all configurations by name and adds a new one
- _append_configuration_ - adds a new configuration

To have some backwards compatibility and to optimize for the most common use cases some of the previous syntaxes are also supported but better defined:

- _conf['k'] = v_ - performs a replace for name 'k' with value (or values) v
- _conf['k']_ - returns the first found value for the name 'k' (assumes we mostly use this for single value keys)
- _del conf['k']_ - removed all values with name 'k'
- _'k' in conf_ - checks if a value with name 'k' exists in the configuration

**Note: The code to save the data back into the .conf file was also changed, which might make it easier to create better formatting, as it's always written at once**

### Configuration UI

The configuration UI was refactored quite a bit and mostly simplified since it can use identifiers to uniquely change configurations

### Node configuration check

Some of the code for checking the default values on each node was simplified with the use of _set_default_configuration_ method.

## TODO

Most tests are likely now broken so they need to be checked and fixed

### CODE REVIEW

**Comment by PierreRochard** [comment]
Fantastic! Massive improvement, thank you @manecosta! 

I was poking around and it seems as though the tor configuration tab is having trouble


image

**Comment by manecosta** [comment]
I wrote a bunch of new tests for the _Configuration_ class and fixed all that had issues now.
### All tests are passing.

**Comment by manecosta** [comment]
This last bugfix should solve the configurations not showing in the UI.

### At this point I'd say the PR is ready.

**Comment by PierreRochard** [comment]
Awesome, thank you @manecosta!

**Pull request merged**
